#############################################################################################
#                    Spring base Configuration                                              #
#############################################################################################
spring.mvc.view.prefix: /view/
spring.mvc.view.suffix: .jsp
server.error.whitelabel.enabled=false
server.error.include-stacktrace=always
server.jsp-servlet.init-parameters.development=true
#############################################################################################

#############################################################################################
#                            App Configuration                                              #
#############################################################################################
server.context-path=/appSync27
#############################################################################################

#############################################################################################
#                              Data Sync Configuration                                      #
#############################################################################################

# Enable or disable the data synchronization scheduler.
# - Master Application  : false  (No scheduler required; master does not initiate sync)
# - Client Application  : true   (Scheduler required to initiate periodic sync)
data.sync.cron.enable = true

# Cron expression that defines how frequently the client application
# will attempt to synchronize data with the master application.
# This property is only applicable when data.sync.cron.enable = true
# Active cron for when enabled
data.sync.cron.expression=0/50 * * * * ?

# Don't change it
data.sync.cron.prop=#{${data.sync.cron.enable:false} ? '${data.sync.cron.expression}' : '0 0 0 1 1 ?'}

# Shared security token used during the handshake process between
# Master and Client applications to authenticate data synchronization requests.
data.sync.handshake.token = SYNC#TOKEN
#############################################################################################

#############################################################################################
#                            DB Configuration                                               #
#############################################################################################
app.db.name=mysql_sync_app_y
#app.db.location=F:/WORK_STATION/SVN-PROJECTS/ZZZ_PROJECT_DB/SQLITE
app.db.location=E:/DBX
#app.db.location=/opt/satcare/sqlite
#############################################################################################

#############################################################################################
#                            logg4j implementation                                          #
#############################################################################################
log4j.rootCategory=INFO, stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] - <%m>%n
log4j.category.org.springframework.web=DEBUG
logging.level.org.springframework.jdbc.core = TRACE
logging.level.org.springframework.web=ERROR
logging.level.ngo.friendship.tms=DEBUG
logging.pattern.console= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#logging.file=F:/LOGS/appSync27/appSync27.log
logging.file=/home/satcare/logs/appSync27/appSync27.log
#############################################################################################



