
-- SQLite database schema for Sync Application

-- User info table
CREATE TABLE IF NOT EXISTS user_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    login_id VARCHAR(20) NOT NULL UNIQUE,  
    password TEXT NOT NULL,
    user_name TEXT NOT NULL,
    state INTEGER DEFAULT 0 CHECK(state IN (0, 1)),
    email TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME
);

-- App properties table
CREATE TABLE IF NOT EXISTS app_properties ( 
    ID INTEGER UNIQUE NOT NULL, 
    NAME VARCHAR (100) NOT NULL, 
    CODE VARCHAR (100) NOT NULL, 
    TYPE VARCHAR (100) NOT NULL,
    STATE NOT NULL DEFAULT (0)
);

-- Client table
CREATE TABLE IF NOT EXISTS client (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR (200), 
    CODE VARCHAR (200) NOT NULL UNIQUE, 
    STATE INTEGER (1) NOT NULL DEFAULT (1)
);

-- Server config table
CREATE TABLE IF NOT EXISTS server_config (
    SERVER_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    SERVER_NAME TEXT NOT NULL, 
    SERVER_ADDRESS TEXT NOT NULL UNIQUE, 
    STATE INT NOT NULL DEFAULT (1)
);

-- Database config table
CREATE TABLE IF NOT EXISTS db_config (
    DB_CONFIG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CONFIG_NAME TEXT NOT NULL UNIQUE,
    DB_URL VARCHAR NOT NULL,
    DB_USER_NAME VARCHAR NOT NULL,
    DB_PASSWORD VARCHAR NOT NULL,
    DB_TYPE VARCHAR,
    SCHEMA TEXT,
    STATE INT NOT NULL DEFAULT (1),
    DB_CONNECTION_STATE INTEGER DEFAULT 0
);

-- Sync table
CREATE TABLE IF NOT EXISTS sync_table (
    TBL_ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    TBL_CODE TEXT UNIQUE, 
    TBL_NAME TEXT NOT NULL, 
    TBL_TYPE TEXT, 
    SERVER_ID INTEGER, 
    DB_CONFIG_ID INTEGER,
    SELECT_SQL TEXT, 
    UPSERT_SQL TEXT, 
    STATE INTEGER, 
    SYNC_PRIORITY INTEGER, 
    CHUNK_SIZE INTEGER NOT NULL DEFAULT (0),
    TBL_PRIMARY_COLUMN TEXT,
    TBL_S_TRACKING_COLUMN TEXT,
    TBL_S_TRACKING_SQL TEXT,
    TBL_C_TRACKING_COLUMN TEXT
);